name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.**
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: # cancel in-progress runs of the same workflow for the same PR, but allow multiple runs for different PRs or for pushes to main
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      msrv-version: ${{ steps.rust-versions.outputs.msrv-version }}
      stable-version: ${{ steps.rust-versions.outputs.stable-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Update rustup
        run: rustup update stable --no-self-update
      - name: Extract Rust versions
        id: rust-versions
        uses: csaf-rs/shared-workflows/.github/actions/rust-versions@4828cd545465d4faade7eb410621ad7d8954f0dc # v1.9.0
      - name: Run shared format and doc checks
        uses: csaf-rs/shared-workflows/.github/actions/rust-checks@4828cd545465d4faade7eb410621ad7d8954f0dc # v1.9.0
        with:
          run-clippy: "false"
      - name: Publish dry-run
        if: github.ref_type != 'tag'
        uses: csaf-rs/shared-workflows/.github/actions/cargo-publish-dry-run@4828cd545465d4faade7eb410621ad7d8954f0dc # v1.9.0

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - ${{ needs.prepare.outputs.msrv-version }}
          - ${{ needs.prepare.outputs.stable-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Update rustup
        run: rustup update stable --no-self-update
      - name: Set Rust version
        run: |
          rustup override set "${{ matrix.version }}"
          rustup default "${{ matrix.version }}"
      - name: Run shared clippy check
        uses: csaf-rs/shared-workflows/.github/actions/rust-checks@4828cd545465d4faade7eb410621ad7d8954f0dc # v1.9.0
        with:
          run-format: "false"
          run-doc: "false"
      - name: Build
        run: cargo build --locked --release --verbose
      - name: Run tests
        run: cargo test --locked --release --verbose

  coverage:
    uses: csaf-rs/shared-workflows/.github/workflows/rust-coverage.yml@4828cd545465d4faade7eb410621ad7d8954f0dc # v1.9.0